kind: project
metadata:
  name: tutorial-shapira
  created: '2022-09-18T08:50:05.381000'
spec:
  functions:
  - url: data-prep.py
    name: data-prep
    kind: job
    image: mlrun/mlrun
    handler: breast_cancer_generator
    with_repo: true
  - url: trainer.py
    name: trainer
    kind: job
    image: mlrun/mlrun
    handler: train
    with_repo: true
  - url: serving.yaml
    name: serving
    with_repo: true
  workflows:
  - path: workflow.py
    name: main
  artifacts: []
  desired_state: online
  owner: shapira
status:
  state: online
